export const GET_AUTH_LOADING ="GET_AUTH_LOADING"
export const GET_AUTH_SUCESS ="GET_AUTH_SUCESS"
export const GET_AUTH_FAILURE ="GET_AUTH_FAILURE"

export const GET_AUTH_LOADING_STUDENT ="GET_AUTH_LOADING_STUDENT"
export const GET_AUTH_SUCESS_STUDENT ="GET_AUTH_SUCESS_STUDENT"
export const GET_AUTH_FAILURE_STUDENT ="GET_AUTH_FAILURE_STUDENT"

export const GET_AUTH_LOADING_COMPANY ="GET_AUTH_LOADING_COMPANY"
export const GET_AUTH_SUCESS_COMPANY ="GET_AUTH_SUCESS_COMPANY"
export const GET_AUTH_FAILURE_COMPANY ="GET_AUTH_FAILURE_COMPANY"