export const GET_PRODUCTS_REQUEST = "GET_PRODUCTS_REQUEST";	
export const GET_PRODUCTS_SUCCESS = "GET_PRODUCTS_SUCCESS";	
export const GET_PRODUCTS_FAILURE = "GET_PRODUCTS_FAILURE";	

// fo User--------------------------------------------------------------------->	
export const ADD_PRODUCT_REQUEST = "ADD_PRODUCT_REQUEST";	
export const ADD_PRODUCT_SUCCESS = "ADD_PRODUCT_SUCCESS";	
export const ADD_PRODUCT_FAILURE = "ADD_PRODUCT_FAILURE";	

export const EDIT_PRODUCT_REQUEST = "EDIT_PRODUCT_REQUEST";	
export const EDIT_PRODUCT_SUCCESS = "EDIT_PRODUCT_SUCCESS";	
export const EDIT_PRODUCT_FAILURE = "EDIT_PRODUCT_FAILURE";	

export const DELETE_PRODUCT_REQUEST = "DELETE_PRODUCT_REQUEST";	
export const DELETE_PRODUCT_SUCCESS = "DELETE_PRODUCT_SUCCESS";	
export const DELETE_PRODUCT_FAILURE = "DELETE_PRODUCT_FAILURE";	


//For Admin----------------------------------------------------------------------->	
export const ADD_PRODUCT_REQUEST_AGAIN = "ADD_PRODUCT_REQUEST_AGAIN";	
export const ADD_PRODUCT_SUCCESS_AGAIN = "ADD_PRODUCT_SUCCESS_AGAIN";	
export const ADD_PRODUCT_FAILURE_AGAIN = "ADD_PRODUCT_FAILURE_AGAIN";	

export const PATCH_BOOK_LOADING ="PATCH_BOOK_LOADING"	
export const PATCH_BOOK_SUCESS ="PATCH_BOOK_SUCESS"	
export const PATCH_BOOK_FAILURE ="PATCH_BOOK_FAILURE"	

export const DELETE_PRODUCT_REQUEST_AGAIN = "DELETE_PRODUCT_REQUEST_AGAIN";	
export const DELETE_PRODUCT_SUCCESS_AGAIN = "DELETE_PRODUCT_SUCCESS_AGAIN";	
export const DELETE_PRODUCT_FAILURE_AGAIN = "DELETE_PRODUCT_FAILURE_AGAIN";	

// fo User cart--------------------------------------------------------------------->	

export const GET_CART_REQUEST = "GET_CART_REQUEST";	
export const GET_CART_SUCCESS = "GET_CART_SUCCESS";	
export const GET_CART_FAILURE = "GET_CART_FAILURE";	

export const ADD_CART_REQUEST = "ADD_CART_REQUEST";	
export const ADD_CART_SUCCESS = "ADD_CART_SUCCESS";	
export const ADD_CART_FAILURE = "ADD_CART_FAILURE";	

export const DELETE_CART_REQUEST = "DELETE_CART_REQUEST";	
export const DELETE_CART_SUCCESS = "DELETE_CART_SUCCESS";	
export const DELETE_CART_FAILURE = "DELETE_CART_FAILURE";	

export const GET_CART_DATA_REQUEST = "GET_CART_DATA_REQUEST";
export const GET_CART_DATA_SUCCESS = "GET_CART_DATA_SUCCESS";
export const GET_CART_DATA_FAILURE = "GET_CART_DATA_FAILURE";

export const DELETE_ALL_CART_DATA_REQUEST = "GET_COURSE_DATA_REQUEST";
export const DELETE_ALL_CART_DATA_SUCCESS = "GET_COURSE_DATA_SUCCESS";
export const DELETE_ALL_CART_DATA_FAILURE = "GET_COURSE_DATA_FAILURE";

