export const GET_JOBS_REQUEST="GET_JOBS_REQUEST"
export const GET_JOBS_SUCCESS="GET_JOBS_SUCCESS"
export const GET_JOBS_FAILURE="GET_JOBS_FAILURE"


export const POST_JOBS_REQUEST="POST_JOBS_REQUEST"
export const POST_JOBS_SUCCESS="POST_JOBS_SUCCESS"
export const POST_JOBS_FAILURE="POST_JOBS_FAILURE"

export const PATCH_JOBS_REQUEST="PATCH_JOBS_REQUEST"
export const PATCH_JOBS_SUCCESS="PATCH_JOBS_SUCCESS"
export const PATCH_JOBS_FAILURE="PATCH_JOBS_FAILURE"


export const DELETE_JOBS_REQUEST="DELETE_JOBS_REQUEST"
export const DELETE_JOBS_SUCCESS="DELETE_JOBS_SUCCESS"
export const DELETE_JOBS_FAILURE="DELETE_JOBS_FAILURE"